#################
# TODO: Fix these:
#################
Lint/Loop:
  Enabled: false

# Offense count: 4
Metrics/BlockNesting:
  Max: 4

# Offense count: 4
Style/DoubleNegation:
  Enabled: false

# Offense count: 6
Style/ModuleFunction:
  Enabled: false

############
# Keep these
############
AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'

Style/GuardClause:
  Enabled: false
